/* patchlev.h
   Header file for uITRON based OS.

   Mods to Original File:
   ----------------------
   a) Added English & removed Japanese comments.

   Copyright Notice:
   -----------------
   Originaly Based on:
   ItIs - ITRON Implementation by Sakamura Lab (Phase3 Release1.3.2)
   (C) Copyright 1989-1996 by Sakamura Lab, the University of Tokyo, JAPAN
   - Japanese version as published at TRON World Wide Web site.
*/
/*===========================================================================*/

#ifndef _PATCHLEVEL_
#define _PATCHLEVEL_

#define MAJOR_REL	1								/* Major Release 	*/
#define MINOR_REL	3								/* Minor Release	*/
#define PATCH_LEVEL	4								/* Patch Level		*/

/*===========================================================================*/
#endif /* _PATCHLEVEL_ */
