/* rtos.h
   Single header file for uITRON based OS.
*/
/*===========================================================================*/

#ifndef _RTOS_
#define _RTOS_

/*---------------------------------------------------------------------------*/

#include "itron.h"
#include "isyscall.h"
#include "errno.h"
#include "config.h"

/*===========================================================================*/

#endif	/* _RTOS_	*/
